@id = aaab4497-68ff-410b-ab03-2a7d015eb8d3

PUT http://localhost:5214/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine dasdsa2",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "lastModifiedDateTime": "2022-04-06T12:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}